### ISSUE TITLE
private key length is invalid

### ISSUE THREAD

**Issue by brandonbryant12** [BitbossIO/keyring#4]
I am experimenting with using keyring instead of the standard BSV package, but I am getting an error, `private key length is invalid` when signing a transaction.

The private key being used is derived like with `bsv.HDPrivateKey` like so 
`pk.deriveChild(nonce).privateKey`

The code runs perfectly fine when using
`const Transaction = bsv.Transaction`

and I get the error when swapping out the line above with 
`const Transaction = require('@keyring/transaction');`

Full error: 

  `RangeError: private key length is invalid
    at Object.publicKey (/node_modules/ecc-tools/lib/index.js:183:24)
    at Input.signableBy (/node_modules/@keyring/transaction/lib/input.js:57:54)`

**Comment by brandonbryant12** [comment]
Here is the example I am working with that produces the error

`
let hex= 0200000001c3eb989d70ef880adea0617e717fee95562e2cb4b171c1ce4e902dfd30623bc4010000006a473044022017d8bca4c3cc1f048244655e067bd742c85b15a296ca75ec10d4907aa39332c302207de401c8c503e0f568ea9798d530eeed367f1c638c1ee3dd87a522e9c451c6c04121029453d8c87a666452429ad7489554a446e2573a546390d6de74bf11531179be01ffffffff02e02e0000000000001976a914bf432fad2ca7748b16ad7f545190c6da40e1ad1c88ac4b1c9305000000001976a914ee5d89576f9e3318172dcb791447f09fe8d4397188ac00000000`


let outputTx = new Transaction(hex)
                .to(route.output.address)
                .fee(fee)
                .sign(Buffer.from('KwoojZViBwEmFGDFsNMnWEEBKLQKCDqF2iSYxv8vmrjR6jEJgX98'));

**Comment by ford152** [comment]
Hi @brandonbryant12 - thanks for reporting this, we'll take a look and get back to you shortly.

**Comment by hexorx** [comment]
@brandonbryant12 the issue is that when you call .toString() on the .privateKey it is returning it in the WIF format but keyring is expecting the actual 32 byte private key in either a buffer or hex string. So you should instead be calling .toBuffer() or .toHex() on pk.deriveChild(nonce).privateKey and passing the result to .sign(). 

We will support the WIF format at some point but it will probably be at a higher level than the transaction package and may be added as a plugin. We will also be adding our own hdkey library soon. Until then you may want to use the hdkey package with keyring since it doesn't require loading the entire bsv package.

**Comment by brandonbryant12** [comment]
I get the same error with private key in hex format
`signing with key 118a44f18b4fe1fa2bacd6e23fa044cc4196f745cf35e8f1e8ff7c8d51764a68`
`error: byte array longer than desired length`

As well as in a buffer 

`signing with private key <Buffer 11 8a 44 f1 8b 4f e1 fa 2b ac d6 e2 3f a0 44 cc 41 96 f7 45 cf 35 e8 f1 e8 ff 7c 8d 51 76 4a 68>`

`exception.caught byte array longer than desired length`

**Comment by hexorx** [comment]
@brandonbryant12 could you give me some more complete  example code and more information. For instance how are you generating the tx hex, and what are you trying to accomplish? Keyring isn't a drop-in replacement for the bsv library and some things may need to be done a little different.

**Comment by brandonbryant12** [comment]
This issue can be closed there was a mistake on my part mixing up the
libraries.  I am all set now!
